[package]
name = "kickscrape"
version = "0.1.0"
edition = "2024"

[dependencies]
fastrand = "2.3.0"
rquest = { version = "5.1.0", features = ["json"] }
rquest-util = "2.2.1"
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["full"] }

[profile.release]
panic = "abort"